//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Forex_Strategy_Builder.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Forex_Strategy_Builder.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap _1day {
            get {
                object obj = ResourceManager.GetObject("_1day", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap account_sett {
            get {
                object obj = ResourceManager.GetObject("account_sett", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap balance_chart {
            get {
                object obj = ResourceManager.GetObject("balance_chart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bar_chart {
            get {
                object obj = ResourceManager.GetObject("bar_chart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bar_explorer {
            get {
                object obj = ResourceManager.GetObject("bar_explorer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;lang&gt;
        ///    
        ///  &lt;!-- Language (This will appear in the menu.) --&gt;
        ///  &lt;language&gt;Български&lt;/language&gt;
        ///  
        ///  &lt;!-- Credits --&gt;
        ///  &lt;translatedby&gt;Forex Software Ltd.&lt;/translatedby&gt;
        ///  &lt;website&gt;http://forexsb.com&lt;/website&gt;
        ///  &lt;corrections&gt;info@forexsb.com&lt;/corrections&gt;
        ///
        ///  &lt;!-- Common --&gt;
        ///  &lt;str&gt;&lt;main&gt;Yes&lt;/main&gt;&lt;alt&gt;Да&lt;/alt&gt;&lt;/str&gt;
        ///  &lt;str&gt;&lt;main&gt;No&lt;/main&gt;&lt;alt&gt;Не&lt;/alt&gt;&lt;/str&gt;
        ///  &lt;str&gt;&lt;main&gt;Ok&lt;/main&gt;&lt;alt&gt;Добре&lt;/alt&gt;&lt;/str&gt;
        ///  &lt;str&gt;&lt;main&gt;Go&lt;/main&gt;&lt;alt&gt;Go&lt;/alt&gt;&lt;/str&gt;
        ///  &lt;str&gt;&lt;main&gt;Start&lt;/main&gt;&lt;a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Bulgarian {
            get {
                return ResourceManager.GetString("Bulgarian", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap calculator {
            get {
                object obj = ResourceManager.GetObject("calculator", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap charges {
            get {
                object obj = ResourceManager.GetObject("charges", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap chart_ambiguous_bars {
            get {
                object obj = ResourceManager.GetObject("chart_ambiguous_bars", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap chart_balance_equity {
            get {
                object obj = ResourceManager.GetObject("chart_balance_equity", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap chart_cross {
            get {
                object obj = ResourceManager.GetObject("chart_cross", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap chart_dinfo_down {
            get {
                object obj = ResourceManager.GetObject("chart_dinfo_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap chart_dinfo_up {
            get {
                object obj = ResourceManager.GetObject("chart_dinfo_up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap chart_dyninfo {
            get {
                object obj = ResourceManager.GetObject("chart_dyninfo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap chart_entry_points {
            get {
                object obj = ResourceManager.GetObject("chart_entry_points", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap chart_floating_pl {
            get {
                object obj = ResourceManager.GetObject("chart_floating_pl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap chart_grid {
            get {
                object obj = ResourceManager.GetObject("chart_grid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap chart_indicators {
            get {
                object obj = ResourceManager.GetObject("chart_indicators", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap chart_lots {
            get {
                object obj = ResourceManager.GetObject("chart_lots", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap chart_pos_price {
            get {
                object obj = ResourceManager.GetObject("chart_pos_price", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap chart_true_charts {
            get {
                object obj = ResourceManager.GetObject("chart_true_charts", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap chart_volume {
            get {
                object obj = ResourceManager.GetObject("chart_volume", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap chart_zoom_in {
            get {
                object obj = ResourceManager.GetObject("chart_zoom_in", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap chart_zoom_out {
            get {
                object obj = ResourceManager.GetObject("chart_zoom_out", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap chat_icon {
            get {
                object obj = ResourceManager.GetObject("chat_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap check_ind {
            get {
                object obj = ResourceManager.GetObject("check_ind", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap clock {
            get {
                object obj = ResourceManager.GetObject("clock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap close_blue {
            get {
                object obj = ResourceManager.GetObject("close_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap close_button {
            get {
                object obj = ResourceManager.GetObject("close_button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap close_image {
            get {
                object obj = ResourceManager.GetObject("close_image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap comparator {
            get {
                object obj = ResourceManager.GetObject("comparator", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap contribute {
            get {
                object obj = ResourceManager.GetObject("contribute", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cumulative_str {
            get {
                object obj = ResourceManager.GetObject("cumulative_str", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap custom_ind {
            get {
                object obj = ResourceManager.GetObject("custom_ind", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap custom_ind_forum {
            get {
                object obj = ResourceManager.GetObject("custom_ind_forum", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap custom_indicators {
            get {
                object obj = ResourceManager.GetObject("custom_indicators", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap data_directory {
            get {
                object obj = ResourceManager.GetObject("data_directory", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap data_horizon {
            get {
                object obj = ResourceManager.GetObject("data_horizon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap down_arrow {
            get {
                object obj = ResourceManager.GetObject("down_arrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap download_data {
            get {
                object obj = ResourceManager.GetObject("download_data", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap duplicate {
            get {
                object obj = ResourceManager.GetObject("duplicate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap edit {
            get {
                object obj = ResourceManager.GetObject("edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap edit_translation {
            get {
                object obj = ResourceManager.GetObject("edit_translation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2000-01-03	00:00	1.0078	1.0281	1.0049	1.0244	20088
        ///2000-01-04	00:00	1.0243	1.0343	1.0211	1.0290	5720
        ///2000-01-05	00:00	1.0291	1.0403	1.0280	1.0325	5981
        ///2000-01-06	00:00	1.0324	1.0415	1.0271	1.0323	7415
        ///2000-01-07	00:00	1.0325	1.0331	1.0252	1.0299	4142
        ///2000-01-10	00:00	1.0292	1.0311	1.0209	1.0251	4846
        ///2000-01-11	00:00	1.0251	1.0341	1.0242	1.0334	5078
        ///2000-01-12	00:00	1.0334	1.0369	1.0262	1.0306	5565
        ///2000-01-13	00:00	1.0306	1.0316	1.0235	1.0258	3117
        ///2000-01-14	00:00	1.0258	1.0276	1.0109	1.0124	8669
        ///2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EURUSD1440 {
            get {
                return ResourceManager.GetString("EURUSD1440", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap exit {
            get {
                object obj = ResourceManager.GetObject("exit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap export {
            get {
                object obj = ResourceManager.GetObject("export", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fast_scan {
            get {
                object obj = ResourceManager.GetObject("fast_scan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fibo_levels {
            get {
                object obj = ResourceManager.GetObject("fibo_levels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap folder_open {
            get {
                object obj = ResourceManager.GetObject("folder_open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap forex_brokers {
            get {
                object obj = ResourceManager.GetObject("forex_brokers", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap forum_icon {
            get {
                object obj = ResourceManager.GetObject("forum_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fx_overview {
            get {
                object obj = ResourceManager.GetObject("fx_overview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap generator {
            get {
                object obj = ResourceManager.GetObject("generator", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap globe {
            get {
                object obj = ResourceManager.GetObject("globe", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap help {
            get {
                object obj = ResourceManager.GetObject("help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap hint {
            get {
                object obj = ResourceManager.GetObject("hint", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon Icon {
            get {
                object obj = ResourceManager.GetObject("Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap info {
            get {
                object obj = ResourceManager.GetObject("info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap information {
            get {
                object obj = ResourceManager.GetObject("information", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap instr_edit {
            get {
                object obj = ResourceManager.GetObject("instr_edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;fsb&gt;
        ///  &lt;instrument&gt;
        ///    &lt;symbol&gt;EURUSD&lt;/symbol&gt;
        ///    &lt;instrumentType&gt;Forex&lt;/instrumentType&gt;
        ///    &lt;comment&gt;Euro vs US Dollar&lt;/comment&gt;
        ///    &lt;digits&gt;4&lt;/digits&gt;
        ///    &lt;contractSize&gt;10000&lt;/contractSize&gt;
        ///    &lt;spread&gt;4&lt;/spread&gt;
        ///    &lt;swapType&gt;pips&lt;/swapType&gt;
        ///    &lt;swapLong&gt;1&lt;/swapLong&gt;
        ///    &lt;swapShort&gt;-1&lt;/swapShort&gt;
        ///    &lt;commissionType&gt;pips&lt;/commissionType&gt;
        ///    &lt;commissionScope&gt;lot&lt;/commissionScope&gt;
        ///    &lt;commissionTime&gt;openclose&lt;/commissionTime&gt;
        ///    &lt;commission&gt;0&lt;/commission&gt;
        ///    &lt;s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string instruments {
            get {
                return ResourceManager.GetString("instruments", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap jforex {
            get {
                object obj = ResourceManager.GetObject("jforex", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lang {
            get {
                object obj = ResourceManager.GetObject("lang", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lang_tools {
            get {
                object obj = ResourceManager.GetObject("lang_tools", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap linked {
            get {
                object obj = ResourceManager.GetObject("linked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Logo {
            get {
                object obj = ResourceManager.GetObject("Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap new_startegy {
            get {
                object obj = ResourceManager.GetObject("new_startegy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap new_translation {
            get {
                object obj = ResourceManager.GetObject("new_translation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap next_gen {
            get {
                object obj = ResourceManager.GetObject("next_gen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap numb_br {
            get {
                object obj = ResourceManager.GetObject("numb_br", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap numb_gr {
            get {
                object obj = ResourceManager.GetObject("numb_gr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap open {
            get {
                object obj = ResourceManager.GetObject("open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap open_image {
            get {
                object obj = ResourceManager.GetObject("open_image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap open_padlock {
            get {
                object obj = ResourceManager.GetObject("open_padlock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap open_padlock_img {
            get {
                object obj = ResourceManager.GetObject("open_padlock_img", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap optimizer {
            get {
                object obj = ResourceManager.GetObject("optimizer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap optimizer_select_all {
            get {
                object obj = ResourceManager.GetObject("optimizer_select_all", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap optimizer_select_none {
            get {
                object obj = ResourceManager.GetObject("optimizer_select_none", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap optimizer_select_random {
            get {
                object obj = ResourceManager.GetObject("optimizer_select_random", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ord_buy {
            get {
                object obj = ResourceManager.GetObject("ord_buy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ord_buy_cancel {
            get {
                object obj = ResourceManager.GetObject("ord_buy_cancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ord_sell {
            get {
                object obj = ResourceManager.GetObject("ord_sell", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ord_sell_cancel {
            get {
                object obj = ResourceManager.GetObject("ord_sell_cancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap overoptimization_chart {
            get {
                object obj = ResourceManager.GetObject("overoptimization_chart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap overview {
            get {
                object obj = ResourceManager.GetObject("overview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap padlock_img {
            get {
                object obj = ResourceManager.GetObject("padlock_img", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap palette {
            get {
                object obj = ResourceManager.GetObject("palette", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pie {
            get {
                object obj = ResourceManager.GetObject("pie", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pivot_points {
            get {
                object obj = ResourceManager.GetObject("pivot_points", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pos_add_long {
            get {
                object obj = ResourceManager.GetObject("pos_add_long", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pos_add_short {
            get {
                object obj = ResourceManager.GetObject("pos_add_short", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pos_buy {
            get {
                object obj = ResourceManager.GetObject("pos_buy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pos_close {
            get {
                object obj = ResourceManager.GetObject("pos_close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pos_revers_long {
            get {
                object obj = ResourceManager.GetObject("pos_revers_long", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pos_revers_short {
            get {
                object obj = ResourceManager.GetObject("pos_revers_short", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pos_sell {
            get {
                object obj = ResourceManager.GetObject("pos_sell", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pos_square {
            get {
                object obj = ResourceManager.GetObject("pos_square", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pos_transfer_long {
            get {
                object obj = ResourceManager.GetObject("pos_transfer_long", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pos_transfer_short {
            get {
                object obj = ResourceManager.GetObject("pos_transfer_short", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap prev_gen {
            get {
                object obj = ResourceManager.GetObject("prev_gen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap profit_calculator {
            get {
                object obj = ResourceManager.GetObject("profit_calculator", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap prompt {
            get {
                object obj = ResourceManager.GetObject("prompt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap publish_strategy {
            get {
                object obj = ResourceManager.GetObject("publish_strategy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap question {
            get {
                object obj = ResourceManager.GetObject("question", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap quick_start {
            get {
                object obj = ResourceManager.GetObject("quick_start", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap recalculate {
            get {
                object obj = ResourceManager.GetObject("recalculate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap reload_data {
            get {
                object obj = ResourceManager.GetObject("reload_data", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap reload_ind {
            get {
                object obj = ResourceManager.GetObject("reload_ind", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap safety_first {
            get {
                object obj = ResourceManager.GetObject("safety_first", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap save {
            get {
                object obj = ResourceManager.GetObject("save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap save_as {
            get {
                object obj = ResourceManager.GetObject("save_as", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap scanner {
            get {
                object obj = ResourceManager.GetObject("scanner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap slot_size_max {
            get {
                object obj = ResourceManager.GetObject("slot_size_max", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap slot_size_mid {
            get {
                object obj = ResourceManager.GetObject("slot_size_mid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap slot_size_min {
            get {
                object obj = ResourceManager.GetObject("slot_size_min", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap str_export_as_ci {
            get {
                object obj = ResourceManager.GetObject("str_export_as_ci", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap str_info_infook {
            get {
                object obj = ResourceManager.GetObject("str_info_infook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap str_info_noinfo {
            get {
                object obj = ResourceManager.GetObject("str_info_noinfo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap str_info_warning {
            get {
                object obj = ResourceManager.GetObject("str_info_warning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Strategy to Indicator: #INDICATORNAME#
        ///// Last changed on #MODIFIED#
        ///// Part of Forex Strategy Builder
        ///// Website http://forexsb.com/
        ///// Copyright (c) 2006 - 2011 Miroslav Popov - All rights reserved.
        ///// This code or any part of it cannot be used in other applications without a permission.
        ///
        ///using System;
        ///using System.Collections.Generic;
        ///
        ///namespace Forex_Strategy_Builder
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Startegy to Indicator
        ///    /// &lt;/summary&gt;
        ///    public class Strategy_To_Indicator : Indicator        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StrategyToIndicator {
            get {
                return ResourceManager.GetString("StrategyToIndicator", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap toggle_journal {
            get {
                object obj = ResourceManager.GetObject("toggle_journal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tools {
            get {
                object obj = ResourceManager.GetObject("tools", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap undo {
            get {
                object obj = ResourceManager.GetObject("undo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap up_arrow {
            get {
                object obj = ResourceManager.GetObject("up_arrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap view_translation {
            get {
                object obj = ResourceManager.GetObject("view_translation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap warning {
            get {
                object obj = ResourceManager.GetObject("warning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
